### ISSUE TITLE
Can't build Goodie Repo - Can't Find Metadata for Deleted IA and IA Page

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-dzp-iachangelog#7]
The current Goodie repo has a diff that removes the `DDG::Goodie::Factorial` because it was integrated into Calculator.pm.

I has "ghosted" the IA Page as the IA was no longer needed.

IAChangelog is throwing an error during build:

```
[IAChangelog] Creating instant answer change log (ia_changelog.yml)
[IAChangelog] Failed to look up metadata for DDG::Goodie::Factorial
[IAChangelog] Failed to look up metadata for DDG::Goodie::Factorial at /opt/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/x86_64-linux/Moose/Meta/Method/Delegation.pm line 113.
[FATAL]  Failure on installation of modules!
...
```

**Comment by zachthompson** [comment]
We now require metadata to do releases, including the removal of instant answers.  Release first, then ghost/delete metadata.
